apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    tier: backend
    component: api 
spec:
  replicas: 2
  selector: 
    matchLabels:
      tier: backend
      component: api 
  
  template:
    metadata:
      labels:
        tier: backend
        component: api 
    spec:
      
      containers:
      - name: backend
        image: "{{ .Values.deployment.image_url }}:{{ .Values.deployment.imageversion }}"
        ports:
        - containerPort: 8080
        
        envFrom:
        - configMapRef:
            name: backend-config