apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
  labels:
    project: expense
spec:
  selector:
    tier: database
    component: mysql
  clusterIP: None
  ports:
  - protocol: TCP 
    port: 3306
    targetPort: 3306