apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: expense
  labels:
    project: expense
spec:
  selector: 
    tier: database
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306