apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    tier: database
    component: mysql
spec: 
  replicas: 2
  serviceName: mysql-headless # head leass service
  minReadySeconds: 10
  
  selector:
    matchLabels:  
      tier: database
      component: mysql
   # Instead of creating a PVC resource, you can directly provide in statefulset
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mysql-sc 
      resources:
        requests:
          storage: {{ .Values.statefulset.storage }}

  template:
    metadata:
      labels:
        tier: database
        component: mysql
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: {{ .Values.statefulset.region }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: "{{ .Values.statefulset.image_url }}:{{ .Values.statefulset.imageversion }}"
        ports:
        - containerPort: 3306

        envFrom:
        - configMapRef:
            name: mysqlconfigmap

        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql

        resources:

          limits:
            memory: "512Mi"     # ✅ Increase to 512Mi or 1Gi
            cpu: "500m"
          requests:
            memory: "256Mi"     # ✅ At least 256Mi for request
            cpu: "250m"